name: CI

on:
  schedule:
    - cron:  '0 23 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # The database backup is in the action run logs. As base64.
      - name: Check availibility and Make database backup on sunday.
        run: |
          curl https://peteris.hopto.org
          [ $(date +%u) -eq 7 ] && curl https://peteris.hopto.org/backupdb | python3 -c "import sys; print(sys.stdin.read(), file=sys.stderr)" || true
