# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # The database backup is in the action run logs. As base64.
      - name: Check availibility and Make database backup on sunday.
        run: |
          curl https://peteris.hopto.org
          [ $(date +%u) -eq 7 ] && curl https://peteris.hopto.org/backupdb | python3 -c "import sys; print(sys.stdin.read(), file=sys.stderr)" || true
